/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task */
        get: operations["get"];
        /** Update a task */
        put: operations["update"];
        post?: never;
        /** Delete a task permanently */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile and preferences */
        get: operations["get_1"];
        /** Update profile and preferences */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a learning card */
        get: operations["get_3"];
        /** Update a learning card (title, description, status) */
        put: operations["update_2"];
        post?: never;
        /** Remove a learning card with its milestones and notes */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a habit */
        get: operations["get_4"];
        /** Update a habit */
        put: operations["update_3"];
        post?: never;
        /** Delete a habit and its completions */
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tasks
         * @description Archived tasks are excluded unless archived=true, which returns only archived tasks.
         */
        get: operations["list"];
        put?: never;
        /** Create a task */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived task */
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a task (status TODO) */
        post: operations["reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a task completed (status DONE) */
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a task */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List plans
         * @description ACTIVE: not started or in progress, by priority. COMPLETED: history, latest first.
         */
        get: operations["list_1"];
        put?: never;
        /** Create a plan from existing tasks, habits and learning resources */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{id}/start-notification/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge a plan's start notification */
        post: operations["acknowledgeStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List learning cards with milestones and notes */
        get: operations["list_2"];
        put?: never;
        /** Add a learning card */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-cards/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a note; returns the card */
        post: operations["addNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-cards/{id}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a milestone; returns the card */
        post: operations["addMilestone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List habits with progress
         * @description active=true/false filters; omit for all
         */
        get: operations["list_3"];
        put?: never;
        /** Create a habit */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a habit */
        post: operations["deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List completions, newest first */
        get: operations["completions"];
        put?: never;
        /** Mark complete for a date (default today); returns the habit with updated progress */
        post: operations["complete_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a habit */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark a plan item done or not done
         * @description A task item also completes/reopens the task; a habit item records/removes today's completion; a learning item changes only the plan.
         */
        patch: operations["setItemDone"];
        trace?: never;
    };
    "/api/learning-cards/{id}/milestones/{milestoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a milestone; returns the card */
        delete: operations["removeMilestone"];
        options?: never;
        head?: never;
        /** Complete/reopen, rename or re-date a milestone; returns the card */
        patch: operations["updateMilestone"];
        trace?: never;
    };
    "/api/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a plan with progress and rest time */
        get: operations["get_2"];
        put?: never;
        post?: never;
        /** Remove a plan */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/start-notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans that have started and not been acknowledged yet */
        get: operations["startNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tasks, habits and learning resources that can be added to a plan */
        get: operations["sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary of tasks, habits, plans and learning for today */
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-cards/{id}/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a note; returns the card */
        delete: operations["removeNote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/habits/{id}/completions/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Undo the completion for a date */
        delete: operations["uncomplete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Status defaults to TODO, priority to MEDIUM */
        TaskRequest: {
            title: string;
            description?: string;
            /** @enum {string} */
            status?: "TODO" | "IN_PROGRESS" | "DONE";
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH";
            /** Format: date */
            dueDate?: string;
        };
        Task: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "TODO" | "IN_PROGRESS" | "DONE";
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH";
            /** Format: date */
            dueDate?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            archived?: boolean;
            /** @description Due before today, not done, not archived */
            overdue?: boolean;
        };
        /** @description User profile and preferences */
        Settings: {
            displayName: string;
            email?: string;
            /**
             * @description IANA timezone that decides what 'today' is
             * @example Asia/Dubai
             */
            timezone: string;
            notificationsEnabled: boolean;
            /** @enum {string} */
            defaultView: "DASHBOARD" | "TASKS" | "HABITS" | "LEARNING" | "PLANS";
        };
        /** @description Status defaults to NOT_STARTED */
        LearningCardRequest: {
            title: string;
            /** @description Description or source: link, book, course name */
            description?: string;
            /** @enum {string} */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
        };
        LearningCard: {
            /** Format: int64 */
            id?: number;
            title?: string;
            description?: string;
            /** @enum {string} */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /** Format: date-time */
            createdAt?: string;
            milestones?: components["schemas"]["Milestone"][];
            notes?: components["schemas"]["Note"][];
            /** Format: int32 */
            milestonesDone?: number;
            /** Format: int32 */
            milestonesTotal?: number;
        };
        Milestone: {
            /** Format: int64 */
            id?: number;
            title?: string;
            done?: boolean;
            /** Format: date */
            targetDate?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        Note: {
            /** Format: int64 */
            id?: number;
            text?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        HabitRequest: {
            name: string;
            description?: string;
            /** @enum {string} */
            frequency: "DAILY" | "WEEKLY";
        };
        Habit: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string;
            /** @enum {string} */
            frequency?: "DAILY" | "WEEKLY";
            /** Format: date-time */
            createdAt?: string;
            active?: boolean;
            progress?: components["schemas"]["HabitProgress"];
        };
        HabitProgress: {
            completedToday?: boolean;
            completedThisPeriod?: boolean;
            /** Format: int32 */
            currentStreak?: number;
            /** Format: int32 */
            totalCompletions?: number;
        };
        /** @description An existing task, habit or learning card */
        PlanItemRef: {
            /** @enum {string} */
            sourceType: "TASK" | "HABIT" | "LEARNING_RESOURCE";
            /** Format: int64 */
            sourceId: number;
        };
        PlanRequest: {
            title: string;
            items: components["schemas"]["PlanItemRef"][];
            /**
             * Format: int32
             * @description Estimated duration in minutes
             */
            estimatedMinutes: number;
            /**
             * Format: date-time
             * @example 2026-09-24T09:00:00+03:00
             */
            startDateTime: string;
            /**
             * Format: date-time
             * @example 2026-09-24T11:00:00+03:00
             */
            endDateTime: string;
            /**
             * Format: int32
             * @description 1 = highest priority
             */
            priorityOrder: number;
        };
        Plan: {
            /** Format: int64 */
            id?: number;
            title?: string;
            /** Format: int32 */
            estimatedMinutes?: number;
            /** Format: date-time */
            startDateTime?: string;
            /** Format: date-time */
            endDateTime?: string;
            /** Format: int32 */
            priorityOrder?: number;
            /** @enum {string} */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /** Format: date-time */
            createdAt?: string;
            items?: components["schemas"]["PlanItem"][];
            /** Format: int32 */
            doneCount?: number;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            progressPercent?: number;
            /**
             * Format: int64
             * @description Seconds until end while IN_PROGRESS, otherwise null
             */
            restSeconds?: number;
            startNotified?: boolean;
            /**
             * Format: date-time
             * @description Server time used for the computation; clients count down from it
             */
            serverTime?: string;
        };
        PlanItem: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            sourceType?: "TASK" | "HABIT" | "LEARNING_RESOURCE";
            /** Format: int64 */
            sourceId?: number;
            title?: string;
            done?: boolean;
            /** @description false when the source was deleted (I-5) */
            sourceAvailable?: boolean;
        };
        NoteRequest: {
            text: string;
        };
        MilestoneRequest: {
            title: string;
            /** Format: date */
            targetDate?: string;
        };
        CompletionRequest: {
            /**
             * Format: date
             * @description Defaults to today; future dates are rejected
             */
            date?: string;
        };
        PlanItemUpdate: {
            done: boolean;
        };
        /** @description Only the fields present are changed */
        MilestoneUpdate: {
            title?: string;
            done?: boolean;
            /** Format: date */
            targetDate?: string;
        };
        PlanSource: {
            /** Format: int64 */
            id?: number;
            title?: string;
        };
        /** @description Items that can be added to a plan (I-18) */
        PlanSources: {
            tasks?: components["schemas"]["PlanSource"][];
            habits?: components["schemas"]["PlanSource"][];
            learningResources?: components["schemas"]["PlanSource"][];
        };
        HabitCompletion: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            habitId?: number;
            /** Format: date */
            completionDate?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description FR-09 summary */
        Dashboard: {
            displayName?: string;
            /** Format: date */
            today?: string;
            /** Format: date-time */
            serverTime?: string;
            tasks?: components["schemas"]["DashboardTasks"];
            habits?: components["schemas"]["DashboardHabits"];
            plans?: components["schemas"]["DashboardPlans"];
            learning?: components["schemas"]["DashboardLearning"];
        };
        DashboardHabits: {
            /** @description Active habits with today's progress */
            today?: components["schemas"]["Habit"][];
            /** Format: int32 */
            active?: number;
            /** Format: int32 */
            completedToday?: number;
        };
        DashboardLearning: {
            cardsByStatus?: {
                [key: string]: number;
            };
            /** Format: int32 */
            milestonesDone?: number;
            /** Format: int32 */
            milestonesTotal?: number;
            /**
             * Format: int32
             * @description Milestones completed in the last 7 days (I-15)
             */
            milestonesCompletedLast7Days?: number;
        };
        DashboardPlans: {
            /** @description In-progress plans with rest time and progress */
            inProgress?: components["schemas"]["Plan"][];
            /** Format: int32 */
            notStarted?: number;
            /** Format: int32 */
            completed?: number;
        };
        DashboardTasks: {
            dueToday?: components["schemas"]["Task"][];
            overdue?: components["schemas"]["Task"][];
            /** Format: int32 */
            completedToday?: number;
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            done?: number;
            /**
             * Format: int32
             * @description Done ÷ all non-archived tasks, rounded (I-16)
             */
            completionPercent?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Settings"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Settings"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningCardRequest"];
            };
        };
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitRequest"];
            };
        };
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                search?: string;
                status?: "TODO" | "IN_PROGRESS" | "DONE";
                priority?: "LOW" | "MEDIUM" | "HIGH";
                due?: "TODAY" | "OVERDUE" | "UPCOMING" | "NONE";
                dueFrom?: string;
                dueTo?: string;
                archived?: boolean;
                sort?: "DUE_DATE" | "CREATED_AT";
                direction?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"][];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    reopen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Task"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                group?: "ACTIVE" | "COMPLETED" | "ALL";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"][];
                };
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
        };
    };
    acknowledgeStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
            /** @description Plan has not started yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"][];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningCardRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    addNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    addMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MilestoneRequest"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"][];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HabitRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
        };
    };
    completions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HabitCompletion"][];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HabitCompletion"][];
                };
            };
        };
    };
    complete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompletionRequest"];
            };
        };
        responses: {
            /** @description Recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Already completed for that date, or habit inactive */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
        };
    };
    setItemDone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                itemId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanItemUpdate"];
            };
        };
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
            /** @description The habit behind the item is inactive */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
        };
    };
    removeMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                milestoneId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    updateMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                milestoneId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MilestoneUpdate"];
            };
        };
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"][];
                };
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Plan"][];
                };
            };
        };
    };
    sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanSources"];
                };
            };
            /** @description Plan or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanSources"];
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    removeNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                noteId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
            /** @description Card, milestone or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LearningCard"];
                };
            };
        };
    };
    uncomplete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
            /** @description Habit not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Habit"];
                };
            };
        };
    };
}
