CREATE TABLE task (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    description  VARCHAR(2000),
    status       VARCHAR(20)   NOT NULL CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE')),
    priority     VARCHAR(10)   NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    due_date     DATE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    is_archived  BOOLEAN NOT NULL DEFAULT FALSE,
    -- BR-5: Done and only Done has a completion time
    CHECK ((status = 'DONE') = (completed_at IS NOT NULL))
);
CREATE INDEX task_due ON task (is_archived, due_date);
