CREATE TABLE habit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(2000),
    frequency   VARCHAR(10)  NOT NULL CHECK (frequency IN ('DAILY', 'WEEKLY')),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE habit_completion (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habit_id        BIGINT NOT NULL REFERENCES habit (id) ON DELETE CASCADE,
    completion_date DATE   NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (habit_id, completion_date)  -- BR-7
);
