CREATE TABLE learning_card (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(20)  NOT NULL CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- BR-9: a milestone belongs to exactly one card
CREATE TABLE learning_milestone (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_card_id BIGINT NOT NULL REFERENCES learning_card (id) ON DELETE CASCADE,
    title            VARCHAR(200) NOT NULL,
    is_done          BOOLEAN NOT NULL DEFAULT FALSE,
    target_date      DATE,
    completed_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE learning_note (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learning_card_id BIGINT NOT NULL REFERENCES learning_card (id) ON DELETE CASCADE,
    text             VARCHAR(5000) NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
