CREATE TABLE plan (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(200) NOT NULL,
    estimated_minutes  INT          NOT NULL CHECK (estimated_minutes > 0),
    start_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    priority_order     INT          NOT NULL CHECK (priority_order > 0),
    status             VARCHAR(20)  NOT NULL CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    start_notified_at  TIMESTAMP WITH TIME ZONE,
    CHECK (end_at > start_at)  -- BR-11
);

CREATE TABLE plan_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id        BIGINT NOT NULL REFERENCES plan (id) ON DELETE CASCADE,
    source_type    VARCHAR(20)  NOT NULL CHECK (source_type IN ('TASK', 'HABIT', 'LEARNING_RESOURCE')),
    source_id      BIGINT       NOT NULL,
    title_snapshot VARCHAR(200) NOT NULL,
    is_done        BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (plan_id, source_type, source_id)
);
